apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-producer
  namespace: node-producer
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: node-producer
  endpoints:
    - port: web-node
