{
 "title": "Accueil",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster" }
  ]
 },
 "panels": [
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://1000logos.net/wp-content/uploads/2022/07/Kubernetes-Logo.jpg\" width=\"200\" height=\"110\"/>"
   }
  },
  {
   "title": "Nombre de pods en cours d'exécution",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de pods / namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Nombre de redémarrage de pods / namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of containers by cluster and namespace without CPU limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory Usage (w/o cache)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Received  [resolution 5min]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=~\".+\"}[4h:5m])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted [resolution 5min]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=~\".+\"}[4h:5m])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 44 },
   "options": {
    "content": "<img src=\"https://fontmeme.com/images/Cassandra-Logo.jpg\" heigt=\"150\" width=\"200\" />"
   }
  },
  {
   "title": "Cluster ops",
   "type": "timeseries",
   "description": "Total aggregated requests per second cluster-wise",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"cassandra\",datacenter=~\"datacenter1\",name=~\"org:apache:cassandra:metrics:clientrequest:(read|write|casread|caswrite|rangeslice|viewwrite):latency:oneminuterate\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"cassandra\",datacenter=~\"datacenter1\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"cassandra\",datacenter=~\"datacenter1\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"cassandra\",datacenter=~\"datacenter1\",name=~\"org:apache:cassandra:metrics:clientrequest:casread:latency:oneminuterate\"})",
     "legendFormat": "CasRead"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"cassandra\",datacenter=~\"datacenter1\",name=~\"org:apache:cassandra:metrics:clientrequest:caswrite:latency:oneminuterate\"})",
     "legendFormat": "CasWrite"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"cassandra\",datacenter=~\"datacenter1\",name=~\"org:apache:cassandra:metrics:clientrequest:rangeslice:latency:oneminuterate\"})",
     "legendFormat": "RangeSlice"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"cassandra\",datacenter=~\"datacenter1\",name=~\"org:apache:cassandra:metrics:clientrequest:viewwrite:latency:oneminuterate\"})",
     "legendFormat": "ViewWrite"
    }
   ]
  },
  { "title": "Node-producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 51 },
   "options": {
    "content": "<img src=\"https://www.t3a.jp/wp-content/uploads/2020/03/nodejs_logo-1024x640.jpg\" height=\"120\" width=\"180\"/>"
   }
  },
  {
   "title": "Nombre d'objets traités par le producer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 51 },
   "targets": [
    { "expr": "object_counter_producer", "legendFormat": "__auto" }
   ]
  },
  { "title": "Python-consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 60 },
   "options": {
    "content": "<img src=\"https://izutsu.aa0.netvolante.jp/pukiwiki/?plugin=ref&page=%E7%94%BB%E5%83%8F%E4%B8%80%E8%A6%A7&src=python_logo.jpg\" height=\"150\" width=\"200\" />"
   }
  },
  {
   "title": "Nombre de gares traitées par le consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 60 },
   "targets": [
    { "expr": "object_counter_gare_consumer", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre de perturbations traitées par le consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 60 },
   "targets": [
    { "expr": "object_counter_pert_consumer", "legendFormat": "__auto" }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 69 },
   "options": {
    "content": "<img src=\"https://logodix.com/logo/2007035.png\" width=\"300\" height=\"150\"/>"
   }
  },
  {
   "title": "Nombre de brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "__auto" }
   ]
  }
 ]
}